import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ProtectedRoute from "../components/ProtectedRoute";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const exemptedRoutes = ["/login", "/register"];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        {/* <ProtectedRoute exemptedRoutes={exemptedRoutes}> */}
        <ToastContainer
          position="top-center"
          autoClose={5000}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss
          pauseOnHover
        />
        <AuthProvider>
          <div className="h-[100px] bg-bgIndlay w-full px-10 py-4 flex items-center justify-between">
            <Image
              src="/images/logo.png"
              width={118}
              height={48}
              alt={"Indlay"}
            />
            {/* <div>{localStorage.getItem("token") && "USER"}</div> */}
          </div>
          {children}
        </AuthProvider>
        {/* </ProtectedRoute> */}
      </body>
    </html>
  );
}
